default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "widgetlab" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "12345678" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>

development:
  <<: *default
  database: widgetlab_development

test:
  <<: *default
  database: widgetlab_test

production:
  <<: *default
  database: widgetlab_production
  username: widgetlab
  password: <%= ENV["WIDGETLAB_DATABASE_PASSWORD"] %>