# Mosquitto configuration file

# Default listener
listener 1883
allow_anonymous true

# WebSocket listener
listener 9001
protocol websockets
allow_anonymous true

# Logging
log_dest stdout
log_type all

